- jbpm-form-modeler-integrations/jbpm-form-modeler-data-modeler/pom.xml
- jbpm-form-modeler-integrations/jbpm-form-modeler-data-modeler/src/main/java/org/jbpm/formModeler/dataModeler/integration/DataModelerService.java
- jbpm-form-modeler-showcase/pom.xml
- jbpm-form-modeler-showcase/src/main/resources/org/jbpm/formModeler/jBPMFormModeler.gwt.xml
Small needed changes to support data modeler
> JBPM-4625 Generation of JPA enabled models

- jbpm-form-modeler-core/jbpm-form-modeler-service/jbpm-form-modeler-form-editor/src/main/resources/org/jbpm/formModeler/components/editor/messages_de.properties
- jbpm-form-modeler-core/jbpm-form-modeler-service/jbpm-form-modeler-form-editor/src/main/resources/org/jbpm/formModeler/components/editor/messages_fr.properties
- jbpm-form-modeler-core/jbpm-form-modeler-service/jbpm-form-modeler-form-editor/src/main/resources/org/jbpm/formModeler/components/editor/messages_pt.properties
- jbpm-form-modeler-core/jbpm-form-modeler-service/jbpm-form-modeler-form-editor/src/main/resources/org/jbpm/formModeler/components/editor/messages_zh.properties
- jbpm-form-modeler-core/jbpm-form-modeler-service/jbpm-form-modeler-service-core/src/main/resources/org/jbpm/formModeler/core/config/fieldTypes/messages_de.properties
- jbpm-form-modeler-core/jbpm-form-modeler-service/jbpm-form-modeler-service-core/src/main/resources/org/jbpm/formModeler/core/config/fieldTypes/messages_es.properties
- jbpm-form-modeler-core/jbpm-form-modeler-service/jbpm-form-modeler-service-core/src/main/resources/org/jbpm/formModeler/core/config/fieldTypes/messages_fr.properties
- jbpm-form-modeler-core/jbpm-form-modeler-service/jbpm-form-modeler-service-core/src/main/resources/org/jbpm/formModeler/core/config/fieldTypes/messages_pt.properties
- jbpm-form-modeler-core/jbpm-form-modeler-service/jbpm-form-modeler-service-core/src/main/resources/org/jbpm/formModeler/core/config/fieldTypes/messages_zh.properties
- jbpm-form-modeler-core/jbpm-form-modeler-service/jbpm-form-modeler-service-core/src/main/resources/org/jbpm/formModeler/core/forms/forms-resources_de.properties
- jbpm-form-modeler-core/jbpm-form-modeler-service/jbpm-form-modeler-service-core/src/main/resources/org/jbpm/formModeler/core/forms/forms-resources_es.properties
- jbpm-form-modeler-core/jbpm-form-modeler-service/jbpm-form-modeler-service-core/src/main/resources/org/jbpm/formModeler/core/forms/forms-resources_fr.properties
- jbpm-form-modeler-core/jbpm-form-modeler-service/jbpm-form-modeler-service-core/src/main/resources/org/jbpm/formModeler/core/forms/forms-resources_pt.properties
- jbpm-form-modeler-core/jbpm-form-modeler-service/jbpm-form-modeler-service-core/src/main/resources/org/jbpm/formModeler/core/forms/forms-resources_zh.properties
- jbpm-form-modeler-core/jbpm-form-modeler-service/jbpm-form-modeler-ui/src/main/resources/org/jbpm/formModeler/core/processing/fieldHandlers/messages_de.properties
- jbpm-form-modeler-core/jbpm-form-modeler-service/jbpm-form-modeler-ui/src/main/resources/org/jbpm/formModeler/core/processing/fieldHandlers/messages_es.properties
- jbpm-form-modeler-core/jbpm-form-modeler-service/jbpm-form-modeler-ui/src/main/resources/org/jbpm/formModeler/core/processing/fieldHandlers/messages_fr.properties
- jbpm-form-modeler-core/jbpm-form-modeler-service/jbpm-form-modeler-ui/src/main/resources/org/jbpm/formModeler/core/processing/fieldHandlers/messages_pt.properties
- jbpm-form-modeler-core/jbpm-form-modeler-service/jbpm-form-modeler-ui/src/main/resources/org/jbpm/formModeler/core/processing/fieldHandlers/messages_zh.properties
- jbpm-form-modeler-core/jbpm-form-modeler-service/jbpm-form-modeler-ui/src/main/resources/org/jbpm/formModeler/core/processing/formRendering/messages_de.properties
- jbpm-form-modeler-core/jbpm-form-modeler-service/jbpm-form-modeler-ui/src/main/resources/org/jbpm/formModeler/core/processing/formRendering/messages_fr.properties
- jbpm-form-modeler-core/jbpm-form-modeler-service/jbpm-form-modeler-ui/src/main/resources/org/jbpm/formModeler/core/processing/formRendering/messages_pt.properties
- jbpm-form-modeler-core/jbpm-form-modeler-service/jbpm-form-modeler-ui/src/main/resources/org/jbpm/formModeler/core/processing/formRendering/messages_zh.properties
- jbpm-form-modeler-field-types/jbpm-form-modeler-document/src/main/resources/org/jbpm/formModeler/fieldTypes/document/messages_de.properties
- jbpm-form-modeler-field-types/jbpm-form-modeler-document/src/main/resources/org/jbpm/formModeler/fieldTypes/document/messages_fr.properties
- jbpm-form-modeler-field-types/jbpm-form-modeler-document/src/main/resources/org/jbpm/formModeler/fieldTypes/document/messages_pt.properties
- jbpm-form-modeler-field-types/jbpm-form-modeler-document/src/main/resources/org/jbpm/formModeler/fieldTypes/document/messages_zh.properties
> added latest Zanata translations for jbpm-form-modeler 6.3.x

- jbpm-form-modeler-showcase/pom.xml
- jbpm-form-modeler-showcase/src/main/resources/org/jbpm/formModeler/jBPMFormModeler.gwt.xml
Added dependencies due this commit: https://github.com/droolsjbpm/kie-wb-common/commit/9f52d009c42860e2c0f60da9f67022ff2a7819a4
> GUVNOR-2278: Added missing dependencies

- jbpm-form-modeler-showcase/src/main/java/org/jbpm/formModeler/server/impl/LuceneConfigProducer.java
See also: 
- https://github.com/droolsjbpm/droolsjbpm-build-bootstrap/pull/169
- https://github.com/uberfire/uberfire/pull/337
- https://github.com/uberfire/uberfire-extensions/pull/258
- https://github.com/droolsjbpm/kie-wb-common/pull/337
- https://github.com/droolsjbpm/jbpm-designer/pull/220
- https://github.com/droolsjbpm/jbpm-form-modeler/pull/46
- https://github.com/droolsjbpm/jbpm-console-ng/pull/395
- https://github.com/droolsjbpm/drools-wb/pull/156
- https://github.com/droolsjbpm/kie-wb-distributions/pull/261
> UF-295 - Upgrading lucene to 5.3.1

- jbpm-form-modeler-showcase/src/main/java/org/jbpm/formModeler/client/ShowcaseEntryPoint.java
- jbpm-form-modeler-showcase/src/main/java/org/jbpm/formModeler/client/home/HomeProducer.java
- jbpm-form-modeler-showcase/src/test/java/org/jbpm/formModeler/client/ShowcaseEntryPointTest.java
Changes required to support the new UF's security APIs
This PR depends on uberfire/uberfire#321
> JBPM-5030: Access control based on the new UF's authz subsystem

- jbpm-form-modeler-panels/jbpm-form-modeler-editor/jbpm-form-modeler-editor-client/pom.xml
- jbpm-form-modeler-panels/jbpm-form-modeler-editor/jbpm-form-modeler-editor-client/src/main/java/org/jbpm/formModeler/editor/client/handlers/NewFormDefinitionHandler.java
- jbpm-form-modeler-panels/jbpm-form-modeler-editor/jbpm-form-modeler-editor-client/src/main/java/org/jbpm/formModeler/editor/client/handlers/NewFormDefinitionlHandler.java
- jbpm-form-modeler-panels/jbpm-form-modeler-editor/jbpm-form-modeler-editor-client/src/test/java/org/jbpm/formModeler/editor/client/handlers/NewFormDefinitionHandlerTest.java
This is one selenium test rewritten as an unit test in community. And a small refactoring to make the testing possible.
> Test for ItemWithThatNameAlreadyExists popup when creating new form.

- jbpm-form-modeler-showcase/pom.xml
Include hibernate dependencies.
@pefernan Please review to fix broken build.
> GUVNOR-2600: Expose Dynamic Bean Validation through DataModelOracle

- jbpm-form-modeler-field-types/jbpm-form-modeler-document/pom.xml
- jbpm-form-modeler-field-types/jbpm-form-modeler-document/src/main/java/org/jbpm/formModeler/fieldTypes/document/handling/JBPMDocumentFieldTypeHandler.java
- jbpm-form-modeler-integrations/jbpm-form-modeler-form-provider/pom.xml
- jbpm-form-modeler-integrations/jbpm-form-modeler-form-provider/src/main/java/org/jbpm/formModeler/kie/services/form/FormManagerService.java
- jbpm-form-modeler-integrations/jbpm-form-modeler-form-provider/src/main/java/org/jbpm/formModeler/kie/services/form/FormProvider.java
- jbpm-form-modeler-integrations/jbpm-form-modeler-form-provider/src/main/java/org/jbpm/formModeler/kie/services/form/ProcessDefinition.java
- jbpm-form-modeler-integrations/jbpm-form-modeler-form-provider/src/main/java/org/jbpm/formModeler/kie/services/form/TaskDefinition.java
- jbpm-form-modeler-integrations/jbpm-form-modeler-form-provider/src/main/java/org/jbpm/formModeler/kie/services/form/finder/RuntimeFormFinder.java
- jbpm-form-modeler-integrations/jbpm-form-modeler-form-provider/src/main/java/org/jbpm/formModeler/kie/services/form/provider/AbstractFormProvider.java
- jbpm-form-modeler-integrations/jbpm-form-modeler-form-provider/src/main/java/org/jbpm/formModeler/kie/services/form/provider/ClasspathFormProvider.java
- jbpm-form-modeler-integrations/jbpm-form-modeler-form-provider/src/main/java/org/jbpm/formModeler/kie/services/form/provider/FormModelerFormProvider.java
- jbpm-form-modeler-integrations/jbpm-form-modeler-form-provider/src/main/java/org/jbpm/formModeler/kie/services/form/provider/FreemakerFormProvider.java
- jbpm-form-modeler-integrations/jbpm-form-modeler-form-provider/src/main/java/org/jbpm/formModeler/kie/services/form/provider/InMemoryFormProvider.java
- jbpm-form-modeler-integrations/jbpm-form-modeler-form-provider/src/main/java/org/jbpm/formModeler/kie/services/impl/FormManagerServiceImpl.java
- jbpm-form-modeler-integrations/jbpm-form-modeler-form-provider/src/main/resources/forms/DefaultProcess.ftl
- jbpm-form-modeler-integrations/jbpm-form-modeler-form-provider/src/main/resources/forms/DefaultTask.ftl
- jbpm-form-modeler-showcase/pom.xml
- jbpm-form-modeler-showcase/src/main/resources/org/jbpm/formModeler/jBPMFormModeler.gwt.xml
depends on https://github.com/droolsjbpm/kie-wb-common/pull/406
> JBPM-5071 - remove of jbpm runtime from workbench

- jbpm-form-modeler-panels/jbpm-form-modeler-editor/jbpm-form-modeler-editor-client/src/main/java/org/jbpm/formModeler/editor/client/editors/FormModelerPanelPresenter.java
This PR updates the usage of PopUps in order to call the new PopUps API (that implements the MVP pattern using Errai UI).
See:
- https://issues.jboss.org/browse/GUVNOR-2431
- https://github.com/uberfire/uberfire/pull/443
> GUVNOR-2431: Redesign Copy, Save, Rename, Restore and Delete Popups (away from FormStylePopup)

- jbpm-form-modeler-core/jbpm-form-modeler-service/jbpm-form-modeler-request-dispatcher/src/main/java/org/jbpm/formModeler/service/bb/mvc/components/handling/BaseUIComponent.java
- jbpm-form-modeler-core/jbpm-form-modeler-service/jbpm-form-modeler-request-dispatcher/src/main/java/org/jbpm/formModeler/service/bb/mvc/components/handling/BeanHandler.java
- jbpm-form-modeler-core/jbpm-form-modeler-service/jbpm-form-modeler-request-dispatcher/src/main/java/org/jbpm/formModeler/service/bb/mvc/controller/responses/ShowCurrentScreenResponse.java
- jbpm-form-modeler-core/jbpm-form-modeler-service/jbpm-form-modeler-request-dispatcher/src/test/java/org/jbpm/formModeler/service/bb/mvc/components/handling/AbstractBeanHandlerTest.java
- jbpm-form-modeler-core/jbpm-form-modeler-service/jbpm-form-modeler-request-dispatcher/src/test/java/org/jbpm/formModeler/service/bb/mvc/components/handling/BaseUIComponentTest.java
- jbpm-form-modeler-core/jbpm-form-modeler-service/jbpm-form-modeler-request-dispatcher/src/test/java/org/jbpm/formModeler/service/bb/mvc/components/handling/BeanHandlerTest.java
- jbpm-form-modeler-core/jbpm-form-modeler-service/jbpm-form-modeler-request-dispatcher/src/test/java/org/jbpm/formModeler/service/bb/mvc/components/handling/mocks/MyBaseUIComponent.java
- jbpm-form-modeler-core/jbpm-form-modeler-service/jbpm-form-modeler-request-dispatcher/src/test/java/org/jbpm/formModeler/service/bb/mvc/components/handling/mocks/MyBeanHandler.java
> JBPM-5219: reseting screem view after a document upload. That prevents errors uploading documents on MultipleSubForms

- jbpm-form-modeler-panels/jbpm-form-modeler-editor/jbpm-form-modeler-editor-client/src/main/java/org/jbpm/formModeler/editor/client/editors/FormModelerPanelPresenter.java
- jbpm-form-modeler-panels/jbpm-form-modeler-editor/jbpm-form-modeler-editor-client/src/main/java/org/jbpm/formModeler/editor/client/type/FormDefinitionResourceType.java
- jbpm-form-modeler-panels/jbpm-form-modeler-editor/jbpm-form-modeler-editor-client/src/test/java/org/jbpm/formModeler/editor/client/editors/FormModelerPanelPresenterTest.java
Fixied issue saving the form to Add the new commits to "Latest Version" control.
> RHBPMS-4239: adding new commits to "Latests Version" control.

- jbpm-form-modeler-showcase/pom.xml
- jbpm-form-modeler-showcase/src/main/java/org/jbpm/formModeler/client/home/HomeProducer.java
- jbpm-form-modeler-showcase/src/main/java/org/jbpm/formModeler/client/i18n/Constants.java
- jbpm-form-modeler-showcase/src/main/resources/org/jbpm/formModeler/client/i18n/Constants.properties
- jbpm-form-modeler-showcase/src/main/resources/org/jbpm/formModeler/jBPMFormModeler.gwt.xml
This adds the Library Perspective missing deps and fixes the build.
> New Library Perspective (new authoring)

- jbpm-form-modeler-showcase/pom.xml
Preference API changed, so I needed to make some minor changes here.
Dependes on: https://github.com/uberfire/uberfire/pull/605
> UF-459: Preference API Refactor

- jbpm-form-modeler-showcase/src/main/java/org/jbpm/formModeler/client/navbar/AppNavBar.html
- jbpm-form-modeler-showcase/src/main/java/org/jbpm/formModeler/client/navbar/AppNavBar.java
Depends on uberfire/uberfire#573
> [UF-443] - Header and Footer should support Errai UI

- jbpm-form-modeler-panels/jbpm-form-modeler-editor/jbpm-form-modeler-editor-client/src/main/java/org/jbpm/formModeler/editor/client/handlers/NewFormDefinitionHandler.java
- jbpm-form-modeler-panels/jbpm-form-modeler-editor/jbpm-form-modeler-editor-client/src/test/java/org/jbpm/formModeler/editor/client/handlers/NewFormDefinitionHandlerTest.java
- jbpm-form-modeler-showcase/pom.xml
* The creation of new resources must be observed by the Library perspective.
> GUVNOR-2851, GUVNOR-2870, GUVNOR-2835: Library perspective

- jbpm-form-modeler-integrations/jbpm-form-modeler-data-modeler/src/main/java/org/jbpm/formModeler/dataModeler/integration/DataModelerService.java
Hello @manstis @pefernan this is just a minor PR derived from the one in kie-wb-commons.
Would you mind review?
Depends on droolsjbpm/kie-wb-common#714
Thanks.
> GUVNOR-2933: Guvnor ALA integration

- jbpm-form-modeler-panels/jbpm-form-modeler-editor/jbpm-form-modeler-editor-client/src/main/java/org/jbpm/formModeler/editor/client/handlers/NewFormDefinitionHandler.java
Cherry picked from master (https://github.com/kiegroup/jbpm-form-modeler/pull/95)
> [7.0.x] GUVNOR-3001: [Library] Business Process asset icon is empty

- jbpm-form-modeler-panels/jbpm-form-modeler-editor/jbpm-form-modeler-editor-backend/src/main/java/org/jbpm/formModeler/panels/modeler/backend/indexing/FormIndexVisitor.java
- jbpm-form-modeler-panels/jbpm-form-modeler-editor/jbpm-form-modeler-editor-backend/src/test/java/org/jbpm/formModeler/panels/modeler/backend/indexing/FormIndexVisitorTest.java
The problem was occuring when the indexed form was including fields with the same name as the Data Holder. Just avoided to index the holder name since the only relevant info there is the type.
@manstis can you take a look?
> GUVNOR-3014: Indexing errors after importing the stock examples

- jbpm-form-modeler-panels/jbpm-form-modeler-editor/jbpm-form-modeler-editor-client/src/main/resources/org/jbpm/formModeler/editor/client/resources/i18n/Constants.properties
@jsoltes can you take a look?
Merge with: https://github.com/kiegroup/kie-wb-common/pull/829
> JBPM-5928: Change Form asset type from Form Definition (Preview) to Form

- jbpm-form-modeler-core/jbpm-form-modeler-api/src/main/java/org/jbpm/formModeler/api/model/Form.java
- jbpm-form-modeler-core/jbpm-form-modeler-service/jbpm-form-modeler-service-core/src/main/java/org/jbpm/formModeler/core/config/FormSerializationManagerImpl.java
- jbpm-form-modeler-core/jbpm-form-modeler-service/jbpm-form-modeler-ui/src/main/java/org/jbpm/formModeler/components/renderer/FormRenderContextManagerImpl.java
depends on https://github.com/kiegroup/droolsjbpm-integration/pull/952
@pefernan @tsurdilo could you please review.
@pefernan I couldn't find a good idea for writing a test for this so any advice is more than welcome
> JBPM-5973 - Subforms are not rendered when provided by KIE Server

- jbpm-form-modeler-core/jbpm-form-modeler-api/src/main/java/org/jbpm/formModeler/api/model/Form.java
- jbpm-form-modeler-core/jbpm-form-modeler-service/jbpm-form-modeler-service-core/src/main/java/org/jbpm/formModeler/core/config/FormSerializationManagerImpl.java
- jbpm-form-modeler-core/jbpm-form-modeler-service/jbpm-form-modeler-ui/src/main/java/org/jbpm/formModeler/components/renderer/FormRenderContextManagerImpl.java
> [7.0.x] JBPM-5973 - Subforms are not rendered when provided by KIE Server

- jbpm-form-modeler-core/jbpm-form-modeler-service/jbpm-form-modeler-ui/src/main/java/org/jbpm/formModeler/core/processing/impl/FormProcessorImpl.java
- jbpm-form-modeler-core/jbpm-form-modeler-service/jbpm-form-modeler-ui/src/test/java/org/jbpm/formModeler/components/renderer/TestFormRenderContextManagerImpl.java
- jbpm-form-modeler-core/jbpm-form-modeler-service/jbpm-form-modeler-ui/src/test/java/org/jbpm/formModeler/core/processing/fieldHandlers/mocks/SubformFinderServiceMock.java
- jbpm-form-modeler-core/jbpm-form-modeler-service/jbpm-form-modeler-ui/src/test/java/org/jbpm/formModeler/core/processing/impl/AbstractFormProcessorImplTest.java
- jbpm-form-modeler-core/jbpm-form-modeler-service/jbpm-form-modeler-ui/src/test/java/org/jbpm/formModeler/core/processing/impl/MultipleSubformAsBasicDataFormProcessorImplTest.java
- jbpm-form-modeler-core/jbpm-form-modeler-service/jbpm-form-modeler-ui/src/test/java/org/jbpm/formModeler/core/processing/impl/SimpleDataFormProcessorImplTest.java
- jbpm-form-modeler-core/jbpm-form-modeler-service/jbpm-form-modeler-ui/src/test/java/org/jbpm/formModeler/core/processing/impl/SubformDataFormProcessorImplTest.java
- jbpm-form-modeler-core/jbpm-form-modeler-service/jbpm-form-modeler-ui/src/test/java/org/jbpm/formModeler/core/processing/impl/model/Address.java
- jbpm-form-modeler-core/jbpm-form-modeler-service/jbpm-form-modeler-ui/src/test/java/org/jbpm/formModeler/core/processing/impl/model/Hobby.java
- jbpm-form-modeler-core/jbpm-form-modeler-service/jbpm-form-modeler-ui/src/test/java/org/jbpm/formModeler/core/processing/impl/model/Person.java
- jbpm-form-modeler-core/jbpm-form-modeler-service/jbpm-form-modeler-ui/src/test/java/org/jbpm/formModeler/core/processing/impl/util/TestFormGenerator.java
@manstis I know it's not your project but could you review it?
@jsoltes can you take a look?
> RHBPMS-4675: List variable is converted to an array of Maps in a User Task if multiple forms

- jbpm-form-modeler-core/jbpm-form-modeler-api/src/main/java/org/jbpm/formModeler/core/config/builders/fieldType/SimpleFieldTypeBuilder.java
- jbpm-form-modeler-core/jbpm-form-modeler-service/jbpm-form-modeler-ui/src/main/java/org/jbpm/formModeler/core/FieldHandlersManagerImpl.java
- jbpm-form-modeler-core/jbpm-form-modeler-service/jbpm-form-modeler-ui/src/main/java/org/jbpm/formModeler/core/processing/fieldHandlers/date/DateFieldHandler.java
- jbpm-form-modeler-core/jbpm-form-modeler-service/jbpm-form-modeler-ui/src/main/java/org/jbpm/formModeler/core/processing/fieldHandlers/date/DateFieldHandlerFormatter.java
- jbpm-form-modeler-core/jbpm-form-modeler-service/jbpm-form-modeler-ui/src/main/java/org/jbpm/formModeler/core/processing/fieldHandlers/date/ShortDateFieldHandler.java
- jbpm-form-modeler-core/jbpm-form-modeler-service/jbpm-form-modeler-ui/src/main/webapp/formModeler/fieldHandlers/Date/input.jsp
- jbpm-form-modeler-core/jbpm-form-modeler-service/jbpm-form-modeler-ui/src/main/webapp/formModeler/fieldHandlers/ShortDate/input.jsp
- jbpm-form-modeler-core/jbpm-form-modeler-service/jbpm-form-modeler-ui/src/test/java/org/jbpm/formModeler/core/processing/fieldHandlers/DefaultFieldHandlerFormatterTest.java
- jbpm-form-modeler-core/jbpm-form-modeler-service/jbpm-form-modeler-ui/src/test/java/org/jbpm/formModeler/core/processing/fieldHandlers/date/AbstractDateFieldHandlerFormatterTest.java
- jbpm-form-modeler-core/jbpm-form-modeler-service/jbpm-form-modeler-ui/src/test/java/org/jbpm/formModeler/core/processing/fieldHandlers/date/DateFieldHandlerFormatterWithDefaultValueTest.java
- jbpm-form-modeler-core/jbpm-form-modeler-service/jbpm-form-modeler-ui/src/test/java/org/jbpm/formModeler/core/processing/fieldHandlers/date/ShortDateFieldHandlerFormatterWithDefaultValueTest.java
@wmedvede  @jsoltes can you check it?
> RHBPMS-4681: Wrong Date is loaded to Date fields when using a defaultvalue formula.

- jbpm-form-modeler-core/jbpm-form-modeler-api/src/main/java/org/jbpm/formModeler/core/config/builders/fieldType/SimpleFieldTypeBuilder.java
- jbpm-form-modeler-core/jbpm-form-modeler-service/jbpm-form-modeler-ui/src/main/java/org/jbpm/formModeler/core/FieldHandlersManagerImpl.java
- jbpm-form-modeler-core/jbpm-form-modeler-service/jbpm-form-modeler-ui/src/main/java/org/jbpm/formModeler/core/processing/fieldHandlers/date/DateFieldHandler.java
- jbpm-form-modeler-core/jbpm-form-modeler-service/jbpm-form-modeler-ui/src/main/java/org/jbpm/formModeler/core/processing/fieldHandlers/date/DateFieldHandlerFormatter.java
- jbpm-form-modeler-core/jbpm-form-modeler-service/jbpm-form-modeler-ui/src/main/java/org/jbpm/formModeler/core/processing/fieldHandlers/date/ShortDateFieldHandler.java
- jbpm-form-modeler-core/jbpm-form-modeler-service/jbpm-form-modeler-ui/src/main/webapp/formModeler/fieldHandlers/Date/input.jsp
- jbpm-form-modeler-core/jbpm-form-modeler-service/jbpm-form-modeler-ui/src/main/webapp/formModeler/fieldHandlers/ShortDate/input.jsp
- jbpm-form-modeler-core/jbpm-form-modeler-service/jbpm-form-modeler-ui/src/test/java/org/jbpm/formModeler/core/processing/fieldHandlers/DefaultFieldHandlerFormatterTest.java
- jbpm-form-modeler-core/jbpm-form-modeler-service/jbpm-form-modeler-ui/src/test/java/org/jbpm/formModeler/core/processing/fieldHandlers/date/AbstractDateFieldHandlerFormatterTest.java
- jbpm-form-modeler-core/jbpm-form-modeler-service/jbpm-form-modeler-ui/src/test/java/org/jbpm/formModeler/core/processing/fieldHandlers/date/DateFieldHandlerFormatterWithDefaultValueTest.java
- jbpm-form-modeler-core/jbpm-form-modeler-service/jbpm-form-modeler-ui/src/test/java/org/jbpm/formModeler/core/processing/fieldHandlers/date/ShortDateFieldHandlerFormatterWithDefaultValueTest.java
Copying changes from https://github.com/kiegroup/jbpm-form-modeler/pull/108
@jsoltes could you take a look?
> RHBPMS-4681: Wrong Date is loaded to Date fields when using a default value formula.

- jbpm-form-modeler-core/jbpm-form-modeler-service/jbpm-form-modeler-ui/src/main/java/org/jbpm/formModeler/core/processing/impl/FormProcessorImpl.java
- jbpm-form-modeler-core/jbpm-form-modeler-service/jbpm-form-modeler-ui/src/test/java/org/jbpm/formModeler/components/renderer/TestFormRenderContextManagerImpl.java
- jbpm-form-modeler-core/jbpm-form-modeler-service/jbpm-form-modeler-ui/src/test/java/org/jbpm/formModeler/core/processing/fieldHandlers/mocks/SubformFinderServiceMock.java
- jbpm-form-modeler-core/jbpm-form-modeler-service/jbpm-form-modeler-ui/src/test/java/org/jbpm/formModeler/core/processing/impl/AbstractFormProcessorImplTest.java
- jbpm-form-modeler-core/jbpm-form-modeler-service/jbpm-form-modeler-ui/src/test/java/org/jbpm/formModeler/core/processing/impl/MultipleSubformAsBasicDataFormProcessorImplTest.java
- jbpm-form-modeler-core/jbpm-form-modeler-service/jbpm-form-modeler-ui/src/test/java/org/jbpm/formModeler/core/processing/impl/SimpleDataFormProcessorImplTest.java
- jbpm-form-modeler-core/jbpm-form-modeler-service/jbpm-form-modeler-ui/src/test/java/org/jbpm/formModeler/core/processing/impl/SubformDataFormProcessorImplTest.java
- jbpm-form-modeler-core/jbpm-form-modeler-service/jbpm-form-modeler-ui/src/test/java/org/jbpm/formModeler/core/processing/impl/model/Address.java
- jbpm-form-modeler-core/jbpm-form-modeler-service/jbpm-form-modeler-ui/src/test/java/org/jbpm/formModeler/core/processing/impl/model/Hobby.java
- jbpm-form-modeler-core/jbpm-form-modeler-service/jbpm-form-modeler-ui/src/test/java/org/jbpm/formModeler/core/processing/impl/model/Person.java
- jbpm-form-modeler-core/jbpm-form-modeler-service/jbpm-form-modeler-ui/src/test/java/org/jbpm/formModeler/core/processing/impl/util/TestFormGenerator.java
Copying changes from https://github.com/kiegroup/jbpm-form-modeler/pull/106
@jsoltes can you take a look?
> RHBPMS-4675: List variable is converted to an array of Maps in a UserTask if multiple forms

- jbpm-form-modeler-showcase/pom.xml
- jbpm-form-modeler-showcase/src/main/resources/org/jbpm/formModeler/jBPMFormModeler.gwt.xml
@manstis this is fixes the build
> JBPM-6017: Fix dependencies on jBPM Form Modeler

- jbpm-form-modeler-showcase/pom.xml
AF-527: aded new appformer maven support artifact for gwt build
> JBPM-6091: jBPM Form Modeler showcase cannot build

- jbpm-form-modeler-panels/jbpm-form-modeler-editor/jbpm-form-modeler-editor-client/src/main/java/org/jbpm/formModeler/editor/client/editors/FormModelerPanelPresenter.java
- jbpm-form-modeler-panels/jbpm-form-modeler-editor/jbpm-form-modeler-editor-client/src/test/java/org/jbpm/formModeler/editor/client/editors/FormModelerPanelPresenterTest.java
See https://issues.jboss.org/browse/JBPM-6069
> JBPM-6069: Missing CRUD buttons in asset editors

- jbpm-form-modeler-showcase/pom.xml
- jbpm-form-modeler-showcase/src/main/resources/org/jbpm/formModeler/jBPMFormModeler.gwt.xml
- pom.xml
Adjust some dependencies due to changes in the Authoring Library => see https://github.com/kiegroup/kie-wb-common/pull/933
@paulovmr Can you approve this dependent PR please?
> JBPM-5876: Fix authoring library dependencies

- jbpm-form-modeler-showcase/src/main/java/org/jbpm/formModeler/client/ShowcaseEntryPoint.java
- jbpm-form-modeler-showcase/src/main/java/org/jbpm/formModeler/client/navbar/AppNavBar.java
- jbpm-form-modeler-showcase/src/test/java/org/jbpm/formModeler/client/ShowcaseEntryPointTest.java
* Remove PlaceManagerActivityService
* Replace @AfterInitialization with @PostConstruct
> AF-546: Reduce startup time of AppFormer apps and workbenches

- jbpm-form-modeler-panels/jbpm-form-modeler-editor/jbpm-form-modeler-editor-backend/src/test/java/org/jbpm/formModeler/panels/modeler/backend/indexing/IndexFormsTest.java
Fixes the IndexFormsTest.
@manstis can you take a look? sorry, a lot of code style changes :S
> JBPM-6177: IndexFormsTest on jbpm-form-modeler is broken

- jbpm-form-modeler-core/jbpm-form-modeler-service/jbpm-form-modeler-ui/src/main/webapp/formModeler/fieldHandlers/Date/input.jsp
- jbpm-form-modeler-core/jbpm-form-modeler-service/jbpm-form-modeler-ui/src/main/webapp/formModeler/fieldHandlers/ShortDate/input.jsp
@jsoltes could you take a look... just a change to this JS code eval
> RHBPMS-4768: "On Change Script Code" does not work properly for ShortDate/Timestamp fields in Form Modeler

- jbpm-form-modeler-showcase/pom.xml
- jbpm-form-modeler-showcase/src/main/resources/org/jbpm/formModeler/jBPMFormModeler.gwt.xml
I had to send this PR again, there was something wrong on the previous one.
@manstis @jsoltes could you review?
This PR is part of an ensemble, please merge with:
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/490
https://github.com/kiegroup/kie-wb-common/pull/1009
https://github.com/kiegroup/drools-wb/pull/561
https://github.com/kiegroup/optaplanner-wb/pull/192
https://github.com/kiegroup/kie-wb-distributions/pull/563
https://github.com/kiegroup/jbpm-wb/pull/817
https://github.com/kiegroup/jbpm-form-modeler/pull/128
> [7.2.x] JBPM-5531: Problems after deleting a form that is used as a subform in other form

- jbpm-form-modeler-showcase/pom.xml
- jbpm-form-modeler-showcase/src/main/resources/org/jbpm/formModeler/jBPMFormModeler.gwt.xml
Copy of https://github.com/kiegroup/jbpm-form-modeler/pull/125
@manstis @jsoltes could you review?
This PR is part of an ensemble, please merge with:
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/508
https://github.com/kiegroup/kie-wb-common/pull/1069
https://github.com/kiegroup/drools-wb/pull/576
https://github.com/kiegroup/optaplanner-wb/pull/201
https://github.com/kiegroup/jbpm-wb/pull/844
https://github.com/kiegroup/kie-wb-distributions/pull/581
https://github.com/kiegroup/jbpm-form-modeler/pull/132
> [7.3.x] JBPM-5531: Problems after deleting a form that is used as a subform in other form.

- jbpm-form-modeler-showcase/pom.xml
- jbpm-form-modeler-showcase/src/main/resources/org/jbpm/formModeler/jBPMFormModeler.gwt.xml
Copy of https://github.com/kiegroup/jbpm-form-modeler/pull/125
@manstis @jsoltes could you review?
This PR is part of an ensemble, please merge with:
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/493
https://github.com/kiegroup/kie-wb-common/pull/1011
https://github.com/kiegroup/drools-wb/pull/564
https://github.com/kiegroup/optaplanner-wb/pull/193
https://github.com/kiegroup/jbpm-wb/pull/819
https://github.com/kiegroup/kie-wb-distributions/pull/565
https://github.com/kiegroup/jbpm-form-modeler/pull/126
> [8.0.x] JBPM-5531: Problems after deleting a form that is used as a subform in other form.

- jbpm-form-modeler-core/jbpm-form-modeler-api/src/main/java/org/jbpm/formModeler/api/client/FormRenderContext.java
- jbpm-form-modeler-core/jbpm-form-modeler-service/jbpm-form-modeler-ui/src/main/java/org/jbpm/formModeler/components/renderer/FormRenderContextManagerImpl.java
- jbpm-form-modeler-field-types/jbpm-form-modeler-document/pom.xml
- jbpm-form-modeler-field-types/jbpm-form-modeler-document/src/main/java/org/jbpm/formModeler/fieldTypes/document/handling/JBPMDocumentFieldTypeHandler.java
- jbpm-form-modeler-field-types/jbpm-form-modeler-document/src/test/java/org/jbpm/formModeler/fieldTypes/document/handling/JBPMDocumentFieldTypeHandlerTest.java
Copy of https://github.com/kiegroup/jbpm-form-modeler/pull/142
@hasys can you take a look?
This is part of an ensemble, merge with:
https://github.com/kiegroup/jbpm/pull/982
https://github.com/kiegroup/kie-wb-common/pull/1163
https://github.com/kiegroup/jbpm-form-modeler/pull/143
https://github.com/kiegroup/jbpm-wb/pull/874
> [7.3.x] JBPM-6047: Uploaded documents not visible on Documents tab on process Instance details

- jbpm-form-modeler-core/jbpm-form-modeler-api/src/main/java/org/jbpm/formModeler/api/client/FormRenderContext.java
- jbpm-form-modeler-core/jbpm-form-modeler-service/jbpm-form-modeler-ui/src/main/java/org/jbpm/formModeler/components/renderer/FormRenderContextManagerImpl.java
- jbpm-form-modeler-field-types/jbpm-form-modeler-document/pom.xml
- jbpm-form-modeler-field-types/jbpm-form-modeler-document/src/main/java/org/jbpm/formModeler/fieldTypes/document/handling/JBPMDocumentFieldTypeHandler.java
- jbpm-form-modeler-field-types/jbpm-form-modeler-document/src/test/java/org/jbpm/formModeler/fieldTypes/document/handling/JBPMDocumentFieldTypeHandlerTest.java
@hasys can you take a look?
This is part of an ensemble, merge with:
https://github.com/kiegroup/jbpm/pull/981
https://github.com/kiegroup/kie-wb-common/pull/1160
https://github.com/kiegroup/jbpm-form-modeler/pull/142
https://github.com/kiegroup/jbpm-wb/pull/873
> [8.0.x] JBPM-6047: Uploaded documents not visible on Documents tab on process Instance details

- jbpm-form-modeler-core/jbpm-form-modeler-service/jbpm-form-modeler-ui/src/main/webapp/formModeler/fieldHandlers/Date/input.jsp
- jbpm-form-modeler-core/jbpm-form-modeler-service/jbpm-form-modeler-ui/src/main/webapp/formModeler/fieldHandlers/ShortDate/input.jsp
> [8.0.x] RHBPMS-4768: "On Change Script Code" does not work properly for ShortDate/Timestamp fields in Form Modeler

- jbpm-form-modeler-core/jbpm-form-modeler-service/jbpm-form-modeler-ui/src/main/webapp/formModeler/fieldHandlers/Date/input.jsp
- jbpm-form-modeler-core/jbpm-form-modeler-service/jbpm-form-modeler-ui/src/main/webapp/formModeler/fieldHandlers/ShortDate/input.jsp
@jsoltes could you review?
@manstis This replaces the changes on: https://github.com/kiegroup/jbpm-form-modeler/pull/136
> [7.3.x] RHBPMS-4768: "On Change Script Code" does not work properly for ShortDate/Timestamp fields in Form Modeler 

- jbpm-form-modeler-core/jbpm-form-modeler-service/jbpm-form-modeler-ui/src/main/webapp/formModeler/fieldHandlers/Date/input.jsp
- jbpm-form-modeler-core/jbpm-form-modeler-service/jbpm-form-modeler-ui/src/main/webapp/formModeler/fieldHandlers/ShortDate/input.jsp
@jsoltes could you please review?
> [6.5.x] RHBPMS-4768: "On Change Script Code" does not work properly for ShortDate/Timestamp fields in Form Modeler

- jbpm-form-modeler-panels/jbpm-form-modeler-editor/jbpm-form-modeler-editor-client/src/main/java/org/jbpm/formModeler/editor/client/editors/FormModelerPanelPresenter.java
- jbpm-form-modeler-panels/jbpm-form-modeler-editor/jbpm-form-modeler-editor-client/src/test/java/org/jbpm/formModeler/editor/client/editors/FormModelerPanelPresenterTest.java
Cherry-picked from [master](https://github.com/kiegroup/jbpm-form-modeler/pull/148).
> [7.4.x] RHBPMS-5008: [Security management] Disabled assets can be edited (#148)
